In [14]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import os, re, nltk, csv, random, string, operator, gensim, warnings, logging, pickle

from collections import Counter

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.stem import WordNetLemmatizer 
from nltk.corpus import wordnet
from nltk.corpus.reader.wordnet import WordNetError

#nltk.download('wordnet')
#nltk.download('punkt')
#nltk.download('stopwords')
#stopwords = stopwords.words('english')

from gensim.models.wrappers import LdaMallet
from gensim.corpora import Dictionary
from gensim.models import CoherenceModel, LdaModel, LsiModel, HdpModel

from sklearn import preprocessing, linear_model, naive_bayes, metrics, svm, ensemble
from sklearn.model_selection import GridSearchCV, train_test_split, KFold, cross_val_score
from sklearn.pipeline import Pipeline
from sklearn.neighbors import KNeighborsClassifier
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.ensemble import VotingClassifier, RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

import io

from google.colab import files
uploaded = files.upload()

#pyLDAvis.enable_notebook()
#warnings.filterwarnings('ignore')
#%matplotlib inline

#logging.basicConfig(format='%(levelname)s : %(message)s', level=logging.INFO)
#logging.root.level = logging.INFO 

Saving email_dump.csv to email_dump.csv


In [0]:
# df = pd.read_csv("C:\Users\GA00612119\Desktop\ML\email_dump.csv", encoding = 'unicode_escape')
df = pd.read_csv(io.BytesIO(uploaded['email_dump.csv']),encoding = 'unicode_escape')

In [18]:
df

Subject        Category
0    Daily Buzz : Last Date for Data Science Hackat...  Learning Bytes
1    International Women's Day 2019 | March 8th Cel...          Social
2                                  Happy Women's Day!!          Social
3    Second Level Escalation email: MFG NDA-Submission       Important
4                                   Happy Women's Day           Social
5                  #BalanceForBetter Happy Women's Day          Social
6    Reminder: Assigned activity NAD 101 to be comp...       Important
7    Learning Assignment Reminder: Rise with Dice D...       Important
8    Reminder: Assigned activity Automation Enginee...       Important
9    Reminder: Assigned activity Code of Ethical Bu...       Important
10   The Daily Buzz: Announcing Technovation – Shar...  Learning Bytes
11                        Thank You Chennai associates          Social
12   International Women's Day 2019 | March 7th Cel...          Social
13                       Ekatvam 2019 - Register NOW!!          Social
14   Learning Bytes: AUTOMATION | PEG | BLOCKCHAIN ...  Learning Bytes
15   International Women's Day 2019 | March 7th Cel...          Social
16   Reminder 1: Insurance Enrollment Window for Pl...       Important
17           NewsNXt: Meet the World's Hardest Workers          Social
18   Learning Assignment Reminder: Rise with Dice D...       Important
19   Reminder: Assigned activity Prevention of Sexu...       Important
20   Reminder: Assigned activity Digital 201 certif...       Important
21   Reminder: Assigned activity Code of Ethical Bu...       Important
22   The Daily Buzz: Wave 2 Write-a-thon: Results a...  Learning Bytes
23   International Women's Day 2019 | March 7th Cel...          Social
24   Important update: Add this number to your mobi...       Important
25   #TechMForPulwamaMartyrs: Help rebuild a broken...          Social
26   RE:  International Women's Day 2019 | March 6t...          Social
27   Reminder: Assigned activity NAD 101 to be comp...       Important
28   Learning Assignment Reminder: Rise with Dice D...       Important
29   Reminder: Assigned activity Code of Ethical Bu...       Important
..                                                 ...             ...
579  Timesheet Approval pending for  01-Jun-19 to 3...       Important
580  Automation Friday Webinar Today | Google Dialo...  Learning Bytes
581  Daily Buzz: Join the Friday Automation webinar...  Learning Bytes
582  REMINDER: Automation Friday Webinar Today | Go...  Learning Bytes
583  JOIN NOW: Automation Friday Webinar Today | Go...  Learning Bytes
584  Reported Time was approved for 01/07/2019 to 3...       Important
585  Purchase requisition 0000192614 POIND raised b...       Important
586  DEXT - Get Ahead Application downtime on Satur...  Learning Bytes
587     Urgent requirement for Java Bangalore location       Important
588  Daily Buzz: Register for sessions in AI, Data ...  Learning Bytes
589  TIM Service Notification - Chennai TMCCC Prima...  Learning Bytes
590                  Your password expires in 7 day(s)       Important
591  TIM Service Notification - Restoration Chennai...       Important
592  Learning Bytes: Check out some important train...  Learning Bytes
593  Inviting volunteers to join the Green Marshals...          Social
594  Daily Buzz: Login to Talex and check out some ...  Learning Bytes
595                            Chennai ACE AWARDS 2019          Social
596                       Training Calendar - Aug 2019  Learning Bytes
597  Daily Buzz: Mahindra has talent is back! The s...  Learning Bytes
598  Learning Bytes: Important technical sessions, ...  Learning Bytes
599  Join us for a Webex session on Women in action...  Learning Bytes
600  Daily Buzz: Know the difference between HUB an...  Learning Bytes
601  Assigned activity Digital 201 certification is...       Important
602  Learning Assignment Overdue: Digital 101 Due b...       Important
603  Automation Friday Webinar | Kofax - An Intelli...  Learning Bytes


In [0]:
train_x, valid_x, train_y, valid_y = train_test_split(df['Subject'], df['Category'],train_size = 0.8,random_state = 1)

In [20]:
tf_vect = TfidfVectorizer(max_df = 1.0, min_df = 1)
tf_vect.fit(df['Subject'])

train_x_tf =  tf_vect.transform(train_x)
valid_x_tf =  tf_vect.transform(valid_x)

encoder = preprocessing.LabelEncoder()
train_y_count = encoder.fit_transform(train_y)
valid_y_count = encoder.fit_transform(valid_y)

train_y_map = dict(zip(encoder.transform(encoder.classes_),encoder.classes_))
valid_y_map = dict(zip(encoder.transform(encoder.classes_),encoder.classes_))

print('train_y_map :',train_y_map,)
print('valid_y_map :',valid_y_map)


train_y_map : {0: 'Important', 1: 'Learning Bytes', 2: 'Social'}
valid_y_map : {0: 'Important', 1: 'Learning Bytes', 2: 'Social'}


In [0]:
grid_params = {'n_neighbors': [3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41],\
              'metric': ['euclidean', 'manhattan'] }

In [0]:
gs = GridSearchCV(KNeighborsClassifier(),\
                  grid_params,\
                  verbose = 1,\
                  cv = 3,\
                  n_jobs = -1)

In [23]:
gs.fit(train_x_tf, train_y_count)

Fitting 3 folds for each of 40 candidates, totalling 120 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done 120 out of 120 | elapsed:    3.1s finished


GridSearchCV(cv=3, error_score='raise-deprecating',
             estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                            metric='minkowski',
                                            metric_params=None, n_jobs=None,
                                            n_neighbors=5, p=2,
                                            weights='uniform'),
             iid='warn', n_jobs=-1,
             param_grid={'metric': ['euclidean', 'manhattan'],
                         'n_neighbors': [3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23,
                                         25, 27, 29, 31, 33, 35, 37, 39, 41]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=1)

In [0]:
pred = gs.predict(valid_x_tf)

In [0]:
acc = accuracy_score(pred, valid_y_count)*100 

In [26]:
print ("********GRID SEARCH RESULTS********")

print("GS Best Score: " + str(gs.best_score_))
print("GS Best Estimator: " + str(gs.best_estimator_))
print("GS Best Params: " + str(gs.best_params_))


********GRID SEARCH RESULTS********
GS Best Score: 0.9096509240246407
GS Best Estimator: KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')
GS Best Params: {'metric': 'euclidean', 'n_neighbors': 3}


In [27]:
print("********MODEL RESULTS*********")
print("Accuracy: " + str(acc) + " %")
print("------------------------------------------------------------------")
print("Confusion Matrix: ")
print(confusion_matrix(valid_y_count, pred))
print("------------------------------------------------------------------")
print("Classification Report: ") 
print(classification_report(valid_y_count, pred))
print("------------------------------------------------------------------")

********MODEL RESULTS*********
Accuracy: 87.70491803278688 %
------------------------------------------------------------------
Confusion Matrix: 
[[54  1  1]
 [ 4 43  1]
 [ 2  6 10]]
------------------------------------------------------------------
Classification Report: 
              precision    recall  f1-score   support

           0       0.90      0.96      0.93        56
           1       0.86      0.90      0.88        48
           2       0.83      0.56      0.67        18

    accuracy                           0.88       122
   macro avg       0.86      0.81      0.83       122
weighted avg       0.87      0.88      0.87       122

------------------------------------------------------------------
